image:
  tag: snyk-fix-08c85f17c94a7f00df6fb21e8ea1d10d
replicaCount: 1

reloader:
  enabled: true

service:
  type: ClusterIP
  port: 80
  targetPort: 8081

environment:
  REDIS_HOSTS: "local:redis-master.redis.svc.cluster.local:6379"